CREATE TABLE TBL_CHANNEL_FILE_INFO_EXPIRED ( 
	PROVINCECODE	VARCHAR(10) NOT NULL,--国内为省份code,海外实际为MCC
	FILENAME    	VARCHAR(100) NOT NULL,
	FILEBYTES		BYTEA NOT NULL,
	STARTPRICE  	NUMERIC(8,0) NOT NULL,
	ENDPRICE    	NUMERIC(8,0) NOT NULL,
	STARTTIME   	TIMESTAMP NULL,
	ENDTIME     	TIMESTAMP NULL,
	CREATETIME  	TIMESTAMP DEFAULT now() NOT NULL 
	);
CREATE TABLE TBL_CHANNEL_FILE_INFO ( 
	PROVINCECODE	VARCHAR(10) NOT NULL,
	FILENAME    	VARCHAR(100) NOT NULL,
	FILEBYTES		BYTEA NOT NULL,
	STARTPRICE  	NUMERIC(8,0) NOT NULL,
	ENDPRICE    	NUMERIC(8,0) NOT NULL,
	STARTTIME   	TIMESTAMP NULL,
	ENDTIME     	TIMESTAMP NULL,
	CREATETIME  	TIMESTAMP DEFAULT now() NOT NULL 
	);

