CREATE TABLE BS_IP_PROVINCE ( 
	ID           	NUMERIC primary key,
	IP_START_NUM 	NUMERIC(12,0) NOT NULL,
	IP_END_NUM   	NUMERIC(12,0) NOT NULL,
	IP_START     	VARCHAR(20) NULL,
	IP_END       	VARCHAR(20) NULL,
	PROVINCE_NAME	VARCHAR(40) NULL,
	PROVINCE_ID  	NUMERIC(10,0) NULL,
	PROVIDER_ID  	NUMERIC(10,0) NULL
)

