--新增系统配置表
CREATE TABLE tbl_system_config(
	D_ID INT(4) NOT NULL AUTO_INCREMENT,
	D_TYPE VARCHAR(64) NOT NULL DEFAULT 'string',
	D_KEY VARCHAR(128) NOT NULL DEFAULT '',
	D_VALUE VARCHAR(100) NOT NULL ,
	D_REMARKS TEXT NULL,
	D_STATUS INT(4) DEFAULT 1,
	D_CREATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	D_MODIFYTIME TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY (D_ID),
	UNIQUE INDEX UNIQUE_tbl_system_config (D_TYPE, D_KEY)
);