CREATE TABLE `tbl_usgs_erathquakeinfo_270_0_eqs` (
	`d_id` VARCHAR(128) NOT NULL,
	`d_date` VARCHAR(128) NULL DEFAULT NULL,
	`d_latitude` VARCHAR(128) NULL DEFAULT NULL,
	`d_longitude` VARCHAR(128) NULL DEFAULT NULL,
	`d_depth` FLOAT NULL DEFAULT NULL,
	`d_magnitude` FLOAT NULL DEFAULT NULL,
	`d_comments` VARCHAR(1024) NULL DEFAULT NULL,
	`d_url` VARCHAR(256) NULL DEFAULT NULL,
	`d_createtime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`d_modifytime` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY (`d_id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;


CREATE TABLE `tbl_usgs_erathquakeinfo_s_america_eqs` (
	`d_id` VARCHAR(128) NOT NULL,
	`d_date` VARCHAR(128) NULL DEFAULT NULL,
	`d_latitude` VARCHAR(128) NULL DEFAULT NULL,
	`d_longitude` VARCHAR(128) NULL DEFAULT NULL,
	`d_depth` FLOAT NULL DEFAULT NULL,
	`d_magnitude` FLOAT NULL DEFAULT NULL,
	`d_comments` VARCHAR(1024) NULL DEFAULT NULL,
	`d_url` VARCHAR(256) NULL DEFAULT NULL,
	`d_createtime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`d_modifytime` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY (`d_id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;


CREATE TABLE `tbl_usgs_erathquakeinfo_90_0_eqs` (
	`d_id` VARCHAR(128) NOT NULL,
	`d_date` VARCHAR(128) NULL DEFAULT NULL,
	`d_latitude` VARCHAR(128) NULL DEFAULT NULL,
	`d_longitude` VARCHAR(128) NULL DEFAULT NULL,
	`d_depth` FLOAT NULL DEFAULT NULL,
	`d_magnitude` FLOAT NULL DEFAULT NULL,
	`d_comments` VARCHAR(1024) NULL DEFAULT NULL,
	`d_url` VARCHAR(256) NULL DEFAULT NULL,
	`d_createtime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`d_modifytime` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY (`d_id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;


CREATE TABLE `tbl_usgs_erathquakeinfo_n_america_eqs` (
	`d_id` VARCHAR(128) NOT NULL,
	`d_date` VARCHAR(128) NULL DEFAULT NULL,
	`d_latitude` VARCHAR(128) NULL DEFAULT NULL,
	`d_longitude` VARCHAR(128) NULL DEFAULT NULL,
	`d_depth` FLOAT NULL DEFAULT NULL,
	`d_magnitude` FLOAT NULL DEFAULT NULL,
	`d_comments` VARCHAR(1024) NULL DEFAULT NULL,
	`d_url` VARCHAR(256) NULL DEFAULT NULL,
	`d_createtime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`d_modifytime` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY (`d_id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;


CREATE TABLE `tbl_usgs_erathquakeinfo_australia_eqs` (
	`d_id` VARCHAR(128) NOT NULL,
	`d_date` VARCHAR(128) NULL DEFAULT NULL,
	`d_latitude` VARCHAR(128) NULL DEFAULT NULL,
	`d_longitude` VARCHAR(128) NULL DEFAULT NULL,
	`d_depth` FLOAT NULL DEFAULT NULL,
	`d_magnitude` FLOAT NULL DEFAULT NULL,
	`d_comments` VARCHAR(1024) NULL DEFAULT NULL,
	`d_url` VARCHAR(256) NULL DEFAULT NULL,
	`d_createtime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`d_modifytime` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY (`d_id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;


CREATE TABLE `tbl_usgs_erathquakeinfo_africa_eqs` (
	`d_id` VARCHAR(128) NOT NULL,
	`d_date` VARCHAR(128) NULL DEFAULT NULL,
	`d_latitude` VARCHAR(128) NULL DEFAULT NULL,
	`d_longitude` VARCHAR(128) NULL DEFAULT NULL,
	`d_depth` FLOAT NULL DEFAULT NULL,
	`d_magnitude` FLOAT NULL DEFAULT NULL,
	`d_comments` VARCHAR(1024) NULL DEFAULT NULL,
	`d_url` VARCHAR(256) NULL DEFAULT NULL,
	`d_createtime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`d_modifytime` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY (`d_id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;


CREATE TABLE `tbl_usgs_erathquakeinfo_270_90_eqs` (
	`d_id` VARCHAR(128) NOT NULL,
	`d_date` VARCHAR(128) NULL DEFAULT NULL,
	`d_latitude` VARCHAR(128) NULL DEFAULT NULL,
	`d_longitude` VARCHAR(128) NULL DEFAULT NULL,
	`d_depth` FLOAT NULL DEFAULT NULL,
	`d_magnitude` FLOAT NULL DEFAULT NULL,
	`d_comments` VARCHAR(1024) NULL DEFAULT NULL,
	`d_url` VARCHAR(256) NULL DEFAULT NULL,
	`d_createtime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`d_modifytime` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY (`d_id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;


CREATE TABLE `tbl_usgs_erathquakeinfo_europe_eqs` (
	`d_id` VARCHAR(128) NOT NULL,
	`d_date` VARCHAR(128) NULL DEFAULT NULL,
	`d_latitude` VARCHAR(128) NULL DEFAULT NULL,
	`d_longitude` VARCHAR(128) NULL DEFAULT NULL,
	`d_depth` FLOAT NULL DEFAULT NULL,
	`d_magnitude` FLOAT NULL DEFAULT NULL,
	`d_comments` VARCHAR(1024) NULL DEFAULT NULL,
	`d_url` VARCHAR(256) NULL DEFAULT NULL,
	`d_createtime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`d_modifytime` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY (`d_id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;


CREATE TABLE `tbl_usgs_erathquakeinfo_270_-90_eqs` (
	`d_id` VARCHAR(128) NOT NULL,
	`d_date` VARCHAR(128) NULL DEFAULT NULL,
	`d_latitude` VARCHAR(128) NULL DEFAULT NULL,
	`d_longitude` VARCHAR(128) NULL DEFAULT NULL,
	`d_depth` FLOAT NULL DEFAULT NULL,
	`d_magnitude` FLOAT NULL DEFAULT NULL,
	`d_comments` VARCHAR(1024) NULL DEFAULT NULL,
	`d_url` VARCHAR(256) NULL DEFAULT NULL,
	`d_createtime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`d_modifytime` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY (`d_id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;


CREATE TABLE `tbl_usgs_erathquakeinfo_s_pacific_eqs` (
	`d_id` VARCHAR(128) NOT NULL,
	`d_date` VARCHAR(128) NULL DEFAULT NULL,
	`d_latitude` VARCHAR(128) NULL DEFAULT NULL,
	`d_longitude` VARCHAR(128) NULL DEFAULT NULL,
	`d_depth` FLOAT NULL DEFAULT NULL,
	`d_magnitude` FLOAT NULL DEFAULT NULL,
	`d_comments` VARCHAR(1024) NULL DEFAULT NULL,
	`d_url` VARCHAR(256) NULL DEFAULT NULL,
	`d_createtime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`d_modifytime` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY (`d_id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE TABLE `tbl_usgs_erathquakeinfo_asia_eqs` (
	`d_id` VARCHAR(128) NOT NULL,
	`d_date` VARCHAR(128) NULL DEFAULT NULL,
	`d_latitude` VARCHAR(128) NULL DEFAULT NULL,
	`d_longitude` VARCHAR(128) NULL DEFAULT NULL,
	`d_depth` FLOAT NULL DEFAULT NULL,
	`d_magnitude` FLOAT NULL DEFAULT NULL,
	`d_comments` VARCHAR(1024) NULL DEFAULT NULL,
	`d_url` VARCHAR(256) NULL DEFAULT NULL,
	`d_createtime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`d_modifytime` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY (`d_id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;