DROP TABLE IF EXISTS TBL_MOBILE_BRAND;
--手机品牌表
CREATE TABLE TBL_MOBILE_BRAND (
	D_ID INT(4) NOT NULL AUTO_INCREMENT, --主键ID
	D_BRAND_ID INT(4) NOT NULL, --品牌ID
	D_CH_NAME VARCHAR(128) NOT NULL DEFAULT '', --品牌名称
	D_EN_NAME VARCHAR(128), -- 品牌英文名
	D_ICON VARCHAR(512), -- 品牌图标
	D_SOURCE SMALLINT(6) NOT NULL DEFAULT '1', -- 品牌来源:泡泡网，中关村
	D_SOURCE_URL VARCHAR(512) NOT NULL DEFAULT '', -- 品牌网址
	D_DESCRIPTION TEXT NULL, -- 品牌描述
    D_CREATE_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,-- 创建时间
    D_MODIFY_DT TIMESTAMP, -- 修改时间
	PRIMARY KEY (D_ID),
    UNIQUE INDEX UNIQUE_TBL_MOBILE_BRAND (D_SOURCE,D_BRAND_ID)
);