DROP TABLE IF EXISTS TBL_SYSCONFIG;
--系统配置信息表
CREATE TABLE TBL_SYSCONFIG (
	D_ID INT(4) NOT NULL AUTO_INCREMENT,
	D_NAME VARCHAR(20) NOT NULL DEFAULT '',
	D_DESCRIPTION VARCHAR(100) NOT NULL DEFAULT '',
	D_GROUPID SMALLINT(6) NOT NULL DEFAULT '1',
	D_TYPE VARCHAR(10) NOT NULL DEFAULT 'string',
	D_VALUE TEXT NULL,
    D_CREATE_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    D_MODIFY_DT TIMESTAMP,
	PRIMARY KEY (D_ID),
    UNIQUE INDEX UNIQUE_TBL_OPERATOR_ROLE (D_NAME)
);

--从另一张表中获取基本数据
INSERT INTO TBL_SYSCONFIG (D_NAME,D_DESCRIPTION,D_GROUPID,D_TYPE,D_VALUE,D_CREATE_DT,D_MODIFY_DT)
SELECT VARNAME,INFO,GROUPID,TYPE,VALUE,NOW(),NOW() FROM DECMS.tbl_sysconfig;