CREATE TABLE TBL_CHANNEL_FILE_INFO_EXPIRED ( 
	PROVINCECODE	VARCHAR2(10) NOT NULL,
	FILENAME    	VARCHAR2(100) NOT NULL,
	FILEBYTES		BLOB NOT NULL,
	STARTPRICE  	NUMBER(8,0) NOT NULL,
	ENDPRICE    	NUMBER(8,0) NOT NULL,
	STARTTIME   	DATE NULL,
	ENDTIME     	DATE NULL,
	CREATETIME  	DATE DEFAULT sysdate NOT NULL 
	);
CREATE TABLE TBL_CHANNEL_FILE_INFO ( 
	PROVINCECODE	VARCHAR2(10) NOT NULL,
	FILENAME    	VARCHAR2(100) NOT NULL,
	FILEBYTES		BLOB NOT NULL,
	STARTPRICE  	NUMBER(8,0) NOT NULL,
	ENDPRICE    	NUMBER(8,0) NOT NULL,
	STARTTIME   	DATE NULL,
	ENDTIME     	DATE NULL,
	CREATETIME  	DATE DEFAULT sysdate NOT NULL 
	);

